// <auto-generated />
using System;
using HomeGarden.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeGarden.Migrations
{
    [DbContext(typeof(HomeGardenDbContext))]
    partial class HomeGardenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeGarden.Models.Alert", b =>
                {
                    b.Property<long>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("alert_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AlertId"));

                    b.Property<DateTime?>("AlertDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("alert_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("alert_type");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("message");

                    b.Property<long>("PlantId")
                        .HasColumnType("bigint")
                        .HasColumnName("plant_id");

                    b.Property<bool?>("Resolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("resolved");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("resolved_at");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("AlertId")
                        .HasName("PK__alerts__4B8FB03AE54D1A27");

                    b.HasIndex("PlantId");

                    b.HasIndex("StatusId");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("HomeGarden.Models.Area", b =>
                {
                    b.Property<long>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("area_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AreaId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("AreaId")
                        .HasName("PK__areas__985D6D6B239D401E");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("areas", (string)null);
                });

            modelBuilder.Entity("HomeGarden.Models.EmailNotification", b =>
                {
                    b.Property<long>("EmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("email_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmailId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("SendTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("send_time")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("Sent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("sent");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime")
                        .HasColumnName("sent_at");

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("subject");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("EmailId")
                        .HasName("PK__email_no__3FEF87664E6515AC");

                    b.HasIndex("UserId");

                    b.ToTable("email_notifications", (string)null);
                });

            modelBuilder.Entity("HomeGarden.Models.EmailTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("template_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<string>("BodyHtml")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body_html");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("subject");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("TemplateId")
                        .HasName("PK__email_te__BE44E07974A8B025");

                    b.HasIndex(new[] { "Code" }, "UQ__email_te__357D4CF9D155981E")
                        .IsUnique()
                        .HasFilter("[code] IS NOT NULL");

                    b.ToTable("email_templates", (string)null);
                });

            modelBuilder.Entity("HomeGarden.Models.HealthDefinition", b =>
                {
                    b.Property<int>("HealthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("health_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.HasKey("HealthId")
                        .HasName("PK__health_d__189960E39E5FD07E");

                    b.ToTable("health_definitions", (string)null);
                });

            modelBuilder.Entity("HomeGarden.Models.MediaFile", b =>
                {
                    b.Property<long>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("file_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FileId"));

                    b.Property<string>("Entity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("entity");

                    b.Property<long?>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_url");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("mime_type");

                    b.Property<decimal?>("SizeKb")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("size_kb");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("FileId")
                        .HasName("PK__media_fi__07D884C6442BAF5D");

                    b.HasIndex("UserId");

                    b.ToTable("media_files", (string)null);
                });

            modelBuilder.Entity("HomeGarden.Models.PaymentProvider", b =>
                {
                    b.Property<int>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("provider_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProviderId"));

                    b.Property<string>("ApiKey")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("api_key");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("EndpointUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("endpoint_url");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("SecretKey")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("secret_key");

                    b.HasKey("ProviderId")
                        .HasName("PK__payment___00E21310C9441459");

                    b.HasIndex(new[] { "Code" }, "UQ__payment___357D4CF9326AF7B0")
                        .IsUnique()
                        .HasFilter("[code] IS NOT NULL");

                    b.ToTable("payment_providers", (string)null);
                });

            modelBuilder.Entity("HomeGarden.Models.Plant", b =>
                {
                    b.Property<long>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("plant_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PlantId"));

                    b.Property<long>("AreaId")
                        .HasColumnType("bigint")
                        .HasColumnName("area_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("HealthId")
                        .HasColumnType("int")
                        .HasColumnName("health_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_url");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("PlantedDate")
                        .HasColumnType("date")
                        .HasColumnName("planted_date");

                    b.Property<string>("Species")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("species");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("PlantId")
                        .HasName("PK__plants__A576B3B458207BB9");

                    b.HasIndex("AreaId");

                    b.HasIndex("HealthId");

                    b.HasIndex("StatusId");

                    b.ToTable("plants", (string)null);
                });

            modelBuilder.Entity("HomeGarden.Models.PlantLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("activity");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<int?>("HealthId")
                        .HasColumnType("int")
                        .HasColumnName("health_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_url");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LogDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("log_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long>("PlantId")
                        .HasColumnType("bigint")
                        .HasColumnName("plant_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("LogId")
                        .HasName("PK__plant_lo__9E2397E05E0A3742");

                    b.HasIndex("HealthId");

                    b.HasIndex("PlantId");

                    b.HasIndex("StatusId");

                    b.ToTable("plant_logs", (string)null);
                });

            modelBuilder.Entity("HomeGarden.Models.PlantResourceUsage", b =>
                {
                    b.Property<long>("UsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("usage_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UsageId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("note");

                    b.Property<long>("PlantId")
                        .HasColumnType("bigint")
                        .HasColumnName("plant_id");

                    b.Property<decimal?>("QuantityUsed")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("quantity_used");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UsedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("used_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UsageId")
                        .HasName("PK__plant_re__B6B13A02021D9E92");

                    b.HasIndex("PlantId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("StatusId");

                    b.ToTable("plant_resource_usage", (string)null);
                });

            modelBuilder.Entity("HomeGarden.Models.Resource", b =>
                {
                    b.Property<long>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("resource_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ResourceId"));

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("cost");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("note");

                    b.Property<decimal?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(1m)
                        .HasColumnName("quantity");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.Property<string>("Unit")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("đơn vị")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("ResourceId")
                        .HasName("PK__resource__4985FC730B20AE78");

                    b.HasIndex("StatusId");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("HomeGarden.Models.ResourceType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.HasKey("TypeId")
                        .HasName("PK__resource__2C0005985FC3A50F");

                    b.ToTable("resource_types", (string)null);
                });

            modelBuilder.Entity("HomeGarden.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role_name");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("RoleId")
                        .HasName("PK__roles__760965CCBC9A0AB9");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "RoleName" }, "UQ__roles__783254B1C41E1C9E")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("HomeGarden.Models.Schedule", b =>
                {
                    b.Property<long>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("schedule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ScheduleId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("frequency");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastDone")
                        .HasColumnType("datetime")
                        .HasColumnName("last_done");

                    b.Property<DateTime>("NextDue")
                        .HasColumnType("datetime")
                        .HasColumnName("next_due");

                    b.Property<long>("PlantId")
                        .HasColumnType("bigint")
                        .HasColumnName("plant_id");

                    b.Property<bool?>("Reminder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("reminder");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("task_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("ScheduleId")
                        .HasName("PK__schedule__C46A8A6FB956B174");

                    b.HasIndex("PlantId");

                    b.HasIndex("StatusId");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("HomeGarden.Models.StatusDefinition", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("entity");

                    b.HasKey("StatusId")
                        .HasName("PK__status_d__3683B53120DA08E7");

                    b.ToTable("status_definitions", (string)null);
                });

            modelBuilder.Entity("HomeGarden.Models.SubscriptionPayment", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Currency")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("VND")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("payment_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("payment_status");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("int")
                        .HasColumnName("provider_id");

                    b.Property<string>("ProviderRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("provider_ref");

                    b.Property<long>("SubscriptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("subscription_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("PaymentId")
                        .HasName("PK__subscrip__ED1FC9EA52CA1362");

                    b.HasIndex("PlanId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("subscription_payments", (string)null);
                });

            modelBuilder.Entity("HomeGarden.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<string>("BillingCycle")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Monthly")
                        .HasColumnName("billing_cycle");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("features");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("price");

                    b.HasKey("PlanId")
                        .HasName("PK__subscrip__BE9F8F1D00E7ACF0");

                    b.ToTable("subscription_plans", (string)null);
                });

            modelBuilder.Entity("HomeGarden.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fullname");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.HasKey("UserId")
                        .HasName("PK__users__B9BE370F5B3BA653");

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E616447E67C59")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HomeGarden.Models.UserNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Channel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("channel");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime")
                        .HasColumnName("read_at");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__user_not__3213E83F371A5221");

                    b.HasIndex("UserId");

                    b.ToTable("user_notifications", (string)null);
                });

            modelBuilder.Entity("HomeGarden.Models.UserSubscription", b =>
                {
                    b.Property<long>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("subscription_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SubscriptionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<long?>("LastPaymentId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_payment_id");

                    b.Property<DateTime>("NextBillingDate")
                        .HasColumnType("datetime")
                        .HasColumnName("next_billing_date");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<DateTime?>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("start_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("SubscriptionId")
                        .HasName("PK__user_sub__863A7EC1F1B43AA2");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("user_subscriptions", (string)null);
                });

            modelBuilder.Entity("HomeGarden.Models.Alert", b =>
                {
                    b.HasOne("HomeGarden.Models.Plant", "Plant")
                        .WithMany("Alerts")
                        .HasForeignKey("PlantId")
                        .IsRequired()
                        .HasConstraintName("FK__alerts__plant_id__7A672E12");

                    b.HasOne("HomeGarden.Models.StatusDefinition", "Status")
                        .WithMany("Alerts")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__alerts__status_i__7B5B524B");

                    b.Navigation("Plant");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("HomeGarden.Models.Area", b =>
                {
                    b.HasOne("HomeGarden.Models.StatusDefinition", "Status")
                        .WithMany("Areas")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__areas__status_id__5EBF139D");

                    b.HasOne("HomeGarden.Models.User", "User")
                        .WithMany("Areas")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__areas__user_id__5DCAEF64");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeGarden.Models.EmailNotification", b =>
                {
                    b.HasOne("HomeGarden.Models.User", "User")
                        .WithMany("EmailNotifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__email_not__user___3F115E1A");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeGarden.Models.MediaFile", b =>
                {
                    b.HasOne("HomeGarden.Models.User", "User")
                        .WithMany("MediaFiles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__media_fil__user___503BEA1C");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeGarden.Models.Plant", b =>
                {
                    b.HasOne("HomeGarden.Models.Area", "Area")
                        .WithMany("Plants")
                        .HasForeignKey("AreaId")
                        .IsRequired()
                        .HasConstraintName("FK__plants__area_id__6383C8BA");

                    b.HasOne("HomeGarden.Models.HealthDefinition", "Health")
                        .WithMany("Plants")
                        .HasForeignKey("HealthId")
                        .HasConstraintName("FK__plants__health_i__656C112C");

                    b.HasOne("HomeGarden.Models.StatusDefinition", "Status")
                        .WithMany("Plants")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__plants__status_i__6477ECF3");

                    b.Navigation("Area");

                    b.Navigation("Health");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("HomeGarden.Models.PlantLog", b =>
                {
                    b.HasOne("HomeGarden.Models.HealthDefinition", "Health")
                        .WithMany("PlantLogs")
                        .HasForeignKey("HealthId")
                        .HasConstraintName("FK__plant_log__healt__73BA3083");

                    b.HasOne("HomeGarden.Models.Plant", "Plant")
                        .WithMany("PlantLogs")
                        .HasForeignKey("PlantId")
                        .IsRequired()
                        .HasConstraintName("FK__plant_log__plant__71D1E811");

                    b.HasOne("HomeGarden.Models.StatusDefinition", "Status")
                        .WithMany("PlantLogs")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__plant_log__statu__72C60C4A");

                    b.Navigation("Health");

                    b.Navigation("Plant");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("HomeGarden.Models.PlantResourceUsage", b =>
                {
                    b.HasOne("HomeGarden.Models.Plant", "Plant")
                        .WithMany("PlantResourceUsages")
                        .HasForeignKey("PlantId")
                        .IsRequired()
                        .HasConstraintName("FK__plant_res__plant__09A971A2");

                    b.HasOne("HomeGarden.Models.Resource", "Resource")
                        .WithMany("PlantResourceUsages")
                        .HasForeignKey("ResourceId")
                        .IsRequired()
                        .HasConstraintName("FK__plant_res__resou__0A9D95DB");

                    b.HasOne("HomeGarden.Models.StatusDefinition", "Status")
                        .WithMany("PlantResourceUsages")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__plant_res__statu__0B91BA14");

                    b.Navigation("Plant");

                    b.Navigation("Resource");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("HomeGarden.Models.Resource", b =>
                {
                    b.HasOne("HomeGarden.Models.StatusDefinition", "Status")
                        .WithMany("Resources")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__resources__statu__03F0984C");

                    b.HasOne("HomeGarden.Models.ResourceType", "Type")
                        .WithMany("Resources")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK__resources__type___02FC7413");

                    b.HasOne("HomeGarden.Models.User", "User")
                        .WithMany("Resources")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__resources__user___02084FDA");

                    b.Navigation("Status");

                    b.Navigation("Type");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeGarden.Models.Role", b =>
                {
                    b.HasOne("HomeGarden.Models.StatusDefinition", "Status")
                        .WithMany("Roles")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK__roles__status_id__52593CB8");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("HomeGarden.Models.Schedule", b =>
                {
                    b.HasOne("HomeGarden.Models.Plant", "Plant")
                        .WithMany("Schedules")
                        .HasForeignKey("PlantId")
                        .IsRequired()
                        .HasConstraintName("FK__schedules__plant__6B24EA82");

                    b.HasOne("HomeGarden.Models.StatusDefinition", "Status")
                        .WithMany("Schedules")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__schedules__statu__6C190EBB");

                    b.Navigation("Plant");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("HomeGarden.Models.SubscriptionPayment", b =>
                {
                    b.HasOne("HomeGarden.Models.SubscriptionPlan", "Plan")
                        .WithMany("SubscriptionPayments")
                        .HasForeignKey("PlanId")
                        .IsRequired()
                        .HasConstraintName("FK__subscript__plan___3A4CA8FD");

                    b.HasOne("HomeGarden.Models.PaymentProvider", "Provider")
                        .WithMany("SubscriptionPayments")
                        .HasForeignKey("ProviderId")
                        .HasConstraintName("FK__subscript__provi__51300E55");

                    b.HasOne("HomeGarden.Models.UserSubscription", "Subscription")
                        .WithMany("SubscriptionPayments")
                        .HasForeignKey("SubscriptionId")
                        .IsRequired()
                        .HasConstraintName("FK__subscript__subsc__3864608B");

                    b.HasOne("HomeGarden.Models.User", "User")
                        .WithMany("SubscriptionPayments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__subscript__user___395884C4");

                    b.Navigation("Plan");

                    b.Navigation("Provider");

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeGarden.Models.User", b =>
                {
                    b.HasOne("HomeGarden.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__users__role_id__5812160E");

                    b.HasOne("HomeGarden.Models.StatusDefinition", "Status")
                        .WithMany("Users")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK__users__status_id__59063A47");

                    b.Navigation("Role");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("HomeGarden.Models.UserNotification", b =>
                {
                    b.HasOne("HomeGarden.Models.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__user_noti__user___4C6B5938");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeGarden.Models.UserSubscription", b =>
                {
                    b.HasOne("HomeGarden.Models.SubscriptionPlan", "Plan")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("PlanId")
                        .IsRequired()
                        .HasConstraintName("FK__user_subs__plan___31B762FC");

                    b.HasOne("HomeGarden.Models.User", "User")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__user_subs__user___30C33EC3");

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeGarden.Models.Area", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("HomeGarden.Models.HealthDefinition", b =>
                {
                    b.Navigation("PlantLogs");

                    b.Navigation("Plants");
                });

            modelBuilder.Entity("HomeGarden.Models.PaymentProvider", b =>
                {
                    b.Navigation("SubscriptionPayments");
                });

            modelBuilder.Entity("HomeGarden.Models.Plant", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("PlantLogs");

                    b.Navigation("PlantResourceUsages");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("HomeGarden.Models.Resource", b =>
                {
                    b.Navigation("PlantResourceUsages");
                });

            modelBuilder.Entity("HomeGarden.Models.ResourceType", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("HomeGarden.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HomeGarden.Models.StatusDefinition", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Areas");

                    b.Navigation("PlantLogs");

                    b.Navigation("PlantResourceUsages");

                    b.Navigation("Plants");

                    b.Navigation("Resources");

                    b.Navigation("Roles");

                    b.Navigation("Schedules");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HomeGarden.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("SubscriptionPayments");

                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("HomeGarden.Models.User", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("EmailNotifications");

                    b.Navigation("MediaFiles");

                    b.Navigation("Resources");

                    b.Navigation("SubscriptionPayments");

                    b.Navigation("UserNotifications");

                    b.Navigation("UserSubscriptions");
                });

            modelBuilder.Entity("HomeGarden.Models.UserSubscription", b =>
                {
                    b.Navigation("SubscriptionPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
